# Generated by Django 2.2.12 on 2022-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=50)),
            ],
        ),
    ]
