# Generated by Django 2.2.12 on 2022-03-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('etd', models.TimeField()),
                ('d_address', models.TextField()),
                ('b_address', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_fk', to='api_app.customers')),
            ],
        ),
    ]
