# Generated by Django 4.0.3 on 2022-03-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('i_id', models.ForeignKey(db_column='i_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_fk', to='api_app.items')),
                ('o_id', models.ForeignKey(db_column='o_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_fk', to='api_app.orders')),
            ],
        ),
    ]
