# Generated by Django 4.0.3 on 2022-03-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='order_details',
            name='o_id',
            field=models.ForeignKey(db_column='o_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='order_fk', serialize=False, to='api_app.orders'),
        ),
    ]
