# Generated by Django 4.0.3 on 2022-03-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_remove_order_details_id_alter_order_details_o_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_fk', to='api_app.items'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='o_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='order_fk', serialize=False, to='api_app.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cust_fk', to='api_app.customers'),
        ),
    ]
