# Generated by Django 4.0.3 on 2022-03-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_order_details_i_id_alter_order_details_o_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_fk', to='api_app.customers'),
        ),
    ]
